### ISSUE TITLE
Support app/stylesheets/app.(sass|scss)

### ISSUE THREAD

**Issue by heycarsten** [minifeed/iridium#3]
Seem good bro?

**Comment by ahawkins** [comment]
please explain. I don't understand.

**Comment by heycarsten** [comment]
Currently only .scss files are matched:

https://github.com/radiumsoftware/iridium/blob/master/lib/iridium/pipeline.rb#L87

This means that you can only use .sass for partials right now.

**Comment by ahawkins** [comment]
Does the scss filter work with sass files? I'm cool with this if it does.
