### ISSUE TITLE
Invalid Gemspec?

### ISSUE THREAD

**Issue by nickw** [minifeed/iridium#30]
I'm getting the following message when installing the iridium gem from Github. It's causing the iridium executable to not be installed which means I can't do much with it. Here's the warning message that bundler gives me:

```
iridium at /path/to/app/vendor/bundle/bundler/gems/iridium-650c33f82cd5 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["generators/iridium/application/templates/Assetfile"] are not files
```

My Gemfile looks like this:

```
source :rubygems

gem "iridium",                    github: "radiumsoftware/iridium"
gem "hydrogen",                   github: "radiumsoftware/hydrogen"

gem "thor",                       "~> 0.16.0"
gem "rake-pipeline",              github: "livingsocial/rake-pipeline" # "~> 0.8.0"
gem "rake-pipeline-web-filters",  "~> 0.7.0"
```

**Comment by ahawkins** [comment]
This is not a problem atm since iridium has to be used with bundler.
Bundler will still find the bin. I'll fix it when a gem is ready.

**Comment by nickw** [comment]
Hmm, but I am using it with bundler. I get the above warning after running `bundle` and then get an error that the executable can't be found when I run `bundle exec iridium`.

**Comment by ahawkins** [comment]
I'm very suspicious of that. I've been using Iridium in it's current form (and the invalid Gemspec) error for weeks with bundler and no problems. I get the error when bundling and haven't seen any problems. What version of bundler are you using?

**Comment by nickw** [comment]
I've tried it with both 1.2.0.rc and 1.2.1.

I do have my `BUNDLE_PATH` set to `vendor/bundle` - not sure if that matters.

**Comment by ahawkins** [comment]
Neither do I. `bundle exec iridium` has never failed me. Strange.
