### ISSUE TITLE
Don't force using rubyracer

### ISSUE THREAD

**Issue by ahx** [minifeed/iridium#37]
ExecJS just works on platforms that already have a JS runtime (like OSX). Some people have a hard time installing V8. Could you remove the dependency on therubyracer?

The commit is here on @drogus fork. This just works for me.
https://github.com/drogus/iridium/commit/493cd9e54b5c3b6bda2f139b28c7704054f22a77

**Comment by ahawkins** [comment]
@ahx Yes I would. What problems would this cause? I believe the only errors would be in runtime in the production environment (when execjs is called).

**Comment by ahx** [comment]
Yes, i think so. If ExecJS cannot find a runtime it should error with "Could not find a JavaScript runtime." (https://github.com/sstephenson/execjs/blob/master/lib/execjs/runtimes.rb#L52)
Sounds ok to me.

**Comment by ahawkins** [comment]
PR it and I'll merge it.
