### ISSUE TITLE
Generate a rackup file by default and remove dev_server.rb

### ISSUE THREAD

**Issue by ahx** [minifeed/iridium#44]
Is there a difference between using iridium server and plain rackup in development? If not, what do you think about generating a config.ru file by default and removing dev_server.rb completely? The handling would be just the same, but things might be a bit more transparent for folks that are already familiar with rackup files.

**Comment by ahawkins** [comment]
Ya there is a difference. `iridium server` includes pipeline reloading. The rackup version does not.
