### ISSUE TITLE
vendor/javascripts folder empty

### ISSUE THREAD

**Issue by dagda1** [minifeed/iridium#5]
Presently the vendor/javascripts directory is empty.

Should minispade.js at the very least not be there?

**Comment by ahawkins** [comment]
@dagda1 update to current master. `vendor/` was in gitignore for some reason. You'll have to generate a new app or add the files manually.

**Comment by dagda1** [comment]
I think you need to commit the change.  The Vendor/ entry is still in .gitignore and the /generators/application/app/vendor/javascripts is stiill empty

**Comment by ahawkins** [comment]
you're right. I committed the change last night and forgot to push it to master. Either way, that's done now.
