### ISSUE TITLE
Automating build

### ISSUE THREAD

**Issue by eltiare** [minifeed/iridium#53]
I'd like to automate the build process for various reasons. Unfortunately `bundle exec iridium build` errors out. Is there any other way to start the build without hitting the server?

**Comment by ahawkins** [comment]
Can you post a trace? There should be no errors.

**Comment by eltiare** [comment]
The command was actually `bundle exec iridium compile`. build doesn't exist. 

Here's the stack trace: https://gist.github.com/eltiare/76480066abc4eb5c4a7e

**Comment by eltiare** [comment]
For whatever it's worth, it happens in Ruby 2.0 but not in Ruby 1.9.3

**Comment by eltiare** [comment]
If I remove the git feature it works just fine. I'll close this for now since I don't get what the feature was for in the first place.
