### ISSUE TITLE
Could not find iridium gem error on OSX Lion, Ruby 1.9.3, RVM

### ISSUE THREAD

**Issue by buzzware** [minifeed/iridium#6]
With this combination I have been unable to get the iridium command to run at all without crashing.

Last login: Wed Aug 15 16:13:29 on ttys000
Using /Users/gary/.rvm/gems/ruby-1.8.7-p358 with gemset rails238
Running /Users/gary/.rvm/hooks/after_use
for rubies: rvm use 1.9.3
for gemsets: rvm gemset use default|global|rails238
for both: rvm use 1.8.7@rails238
for gems, don't use sudo
GaryMac:~ gary$ rvm use 1.9.3@ir
Using /Users/gary/.rvm/gems/ruby-1.9.3-p194 with gemset ir
Running /Users/gary/.rvm/hooks/after_use
GaryMac:~ gary$ cd repos/emberCalc/adviserConsole2/source/
GaryMac:source gary$ ls
Gemfile     Gemfile.lock
GaryMac:source gary$ bundle exec iridium 
Tasks:
  iridium app PATH     # generate a new application in PATH
  iridium compile      # compile assets for deployment
  iridium help [TASK]  # Describe available tasks or one specific task
  iridium server       # start a development server

GaryMac:source gary$ iridium help
/Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find iridium (>= 0) amongst [POpen4-0.1.4, Platform-0.4.0, activesupport-3.2.8, bundler-1.1.5, bundler-1.1.3, chunky_png-1.2.6, coffee-script-2.2.0, coffee-script-source-1.3.3, commonjs-0.2.6, compass-0.12.2, daemons-1.1.9, eventmachine-0.12.10, execjs-1.4.0, fssm-0.2.9, i18n-0.6.0, less-2.2.1, libv8-3.3.10.4-x86_64-darwin-11, multi_json-1.3.6, open4-1.3.0, rack-1.4.1, rack-rewrite-1.2.1, rake-0.9.2.2, rubygems-bundler-0.9.0, rvm-1.11.3.3, sass-3.2.0, therubyracer-0.10.2, thin-1.4.1, thor-0.16.0, uglifier-1.2.7, yui-compressor-0.9.6] (Gem::LoadError)
    from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems.rb:1231:in `gem'
    from /Users/gary/.rvm/gems/ruby-1.9.3-p194@ir/bin/iridium:22:in`<main>'
GaryMac:source gary$ gem list --local

**\* LOCAL GEMS ***

activesupport (3.2.8)
bundler (1.1.5, 1.1.3)
chunky_png (1.2.6)
coffee-script (2.2.0)
coffee-script-source (1.3.3)
commonjs (0.2.6)
compass (0.12.2)
daemons (1.1.9)
eventmachine (0.12.10)
execjs (1.4.0)
fssm (0.2.9)
i18n (0.6.0)
less (2.2.1)
libv8 (3.3.10.4 x86_64-darwin-11)
multi_json (1.3.6)
open4 (1.3.0)
Platform (0.4.0)
POpen4 (0.1.4)
rack (1.4.1)
rack-rewrite (1.2.1)
rake (0.9.2.2)
rubygems-bundler (0.9.0)
rvm (1.11.3.3)
sass (3.2.0)
therubyracer (0.10.2)
thin (1.4.1)
thor (0.16.0)
uglifier (1.2.7)
yui-compressor (0.9.6)
GaryMac:source gary$ cat Gemfile
source :rubygems

gem 'iridium', :github => 'radiumsoftware/iridium'
gem "rake-pipeline", :github => "livingsocial/rake-pipeline"
gem "rake-pipeline-web-filters", :github => "wycats/rake-pipeline-web-filters"

GaryMac:source gary$ cat Gemfile.lock 
GIT
  remote: git://github.com/livingsocial/rake-pipeline.git
  revision: 3465e0e3e134bf52ddf5d138e8c8262412080095
  specs:
    rake-pipeline (0.6.0)
      rake (~> 0.9.0)
      thor

GIT
  remote: git://github.com/radiumsoftware/iridium.git
  revision: f97129803d10b12c790c031366ce3a3866afcdbe
  specs:
    iridium (0.2.0)
      activesupport
      coffee-script
      compass
      execjs
      less
      rack
      rack-rewrite
      rake-pipeline
      rake-pipeline-web-filters
      sass
      therubyracer
      thin
      thor
      uglifier (~> 1.2.3)
      yui-compressor

GIT
  remote: git://github.com/wycats/rake-pipeline-web-filters.git
  revision: 51915f60889fbf54fc2e81b86b594bf4c7be4ea5
  specs:
    rake-pipeline-web-filters (0.6.0)
      rack
      rake-pipeline (~> 0.6)

GEM
  remote: http://rubygems.org/
  specs:
    POpen4 (0.1.4)
      Platform (>= 0.4.0)
      open4
    Platform (0.4.0)
    activesupport (3.2.8)
      i18n (~> 0.6)
      multi_json (~> 1.0)
    chunky_png (1.2.6)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.3.3)
    commonjs (0.2.6)
    compass (0.12.2)
      chunky_png (~> 1.2)
      fssm (>= 0.2.7)
      sass (~> 3.1)
    daemons (1.1.9)
    eventmachine (0.12.10)
    execjs (1.4.0)
      multi_json (~> 1.0)
    fssm (0.2.9)
    i18n (0.6.0)
    less (2.2.1)
      commonjs (~> 0.2.6)
    libv8 (3.3.10.4)
    multi_json (1.3.6)
    open4 (1.3.0)
    rack (1.4.1)
    rack-rewrite (1.2.1)
    rake (0.9.2.2)
    sass (3.2.0)
    therubyracer (0.10.2)
      libv8 (~> 3.3.10)
    thin (1.4.1)
      daemons (>= 1.0.9)
      eventmachine (>= 0.12.6)
      rack (>= 1.0.0)
    thor (0.16.0)
    uglifier (1.2.7)
      execjs (>= 0.3.0)
      multi_json (~> 1.3)
    yui-compressor (0.9.6)
      POpen4 (>= 0.1.4)

PLATFORMS
  ruby

DEPENDENCIES
  iridium!
  rake-pipeline!
  rake-pipeline-web-filters!
GaryMac:source gary$ rm Gemfile.lock 
GaryMac:source gary$ bundle exec iridium 
git://github.com/radiumsoftware/iridium.git (at master) is not checked out. Please run `bundle install`
GaryMac:source gary$ bundle install
Updating git://github.com/radiumsoftware/iridium.git
Updating git://github.com/livingsocial/rake-pipeline.git
Updating git://github.com/wycats/rake-pipeline-web-filters.git
Fetching gem metadata from http://rubygems.org/........
Using rake (0.9.2.2) 
Using Platform (0.4.0) 
Using open4 (1.3.0) 
Using POpen4 (0.1.4) 
Using i18n (0.6.0) 
Using multi_json (1.3.6) 
Using activesupport (3.2.8) 
Using chunky_png (1.2.6) 
Using coffee-script-source (1.3.3) 
Using execjs (1.4.0) 
Using coffee-script (2.2.0) 
Using commonjs (0.2.6) 
Using fssm (0.2.9) 
Installing sass (3.2.1) 
Using compass (0.12.2) 
Using daemons (1.1.9) 
Using eventmachine (0.12.10) 
Using less (2.2.1) 
Using rack (1.4.1) 
Using rack-rewrite (1.2.1) 
Using thor (0.16.0) 
Using rake-pipeline (0.6.0) from git://github.com/livingsocial/rake-pipeline.git (at master) 
Using rake-pipeline-web-filters (0.6.0) from git://github.com/wycats/rake-pipeline-web-filters.git (at master) 
Using libv8 (3.3.10.4) 
Using therubyracer (0.10.2) 
Using thin (1.4.1) 
Using uglifier (1.2.7) 
Using yui-compressor (0.9.6) 
Using iridium (0.2.0) from git://github.com/radiumsoftware/iridium.git (at master) 
Using bundler (1.1.5) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
GaryMac:source gary$ bundle exec iridium 
Tasks:
  iridium app PATH     # generate a new application in PATH
  iridium compile      # compile assets for deployment
  iridium help [TASK]  # Describe available tasks or one specific task
  iridium server       # start a development server

GaryMac:source gary$ iridium help
/Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find iridium (>= 0) amongst [POpen4-0.1.4, Platform-0.4.0, activesupport-3.2.8, bundler-1.1.5, bundler-1.1.3, chunky_png-1.2.6, coffee-script-2.2.0, coffee-script-source-1.3.3, commonjs-0.2.6, compass-0.12.2, daemons-1.1.9, eventmachine-0.12.10, execjs-1.4.0, fssm-0.2.9, i18n-0.6.0, less-2.2.1, libv8-3.3.10.4-x86_64-darwin-11, multi_json-1.3.6, open4-1.3.0, rack-1.4.1, rack-rewrite-1.2.1, rake-0.9.2.2, rubygems-bundler-0.9.0, rvm-1.11.3.3, sass-3.2.1, sass-3.2.0, therubyracer-0.10.2, thin-1.4.1, thor-0.16.0, uglifier-1.2.7, yui-compressor-0.9.6] (Gem::LoadError)
    from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems.rb:1231:in `gem'
    from /Users/gary/.rvm/gems/ruby-1.9.3-p194@ir/bin/iridium:22:in`<main>'
GaryMac:source gary$ 

Last login: Fri Aug 17 00:56:09 on ttys000
Using /Users/gary/.rvm/gems/ruby-1.8.7-p358 with gemset rails238
Running /Users/gary/.rvm/hooks/after_use
for rubies: rvm use 1.9.3
for gemsets: rvm gemset use default|global|rails238
for both: rvm use 1.8.7@rails238
for gems, don't use sudo
garymac:~ gary$ rvm use 1.9.3@ir
Using /Users/gary/.rvm/gems/ruby-1.9.3-p194 with gemset ir
Running /Users/gary/.rvm/hooks/after_use
garymac:~ gary$ cd repos/emberCalc/adviserConsole2/source/
garymac:source gary$ ls
Gemfile     Gemfile.lock
garymac:source gary$ iridium server
/Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find iridium (>= 0) amongst [POpen4-0.1.4, Platform-0.4.0, activesupport-3.2.8, bundler-1.1.5, bundler-1.1.3, chunky_png-1.2.6, coffee-script-2.2.0, coffee-script-source-1.3.3, commonjs-0.2.6, compass-0.12.2, daemons-1.1.9, eventmachine-0.12.10, execjs-1.4.0, fssm-0.2.9, i18n-0.6.0, less-2.2.1, libv8-3.3.10.4-x86_64-darwin-11, multi_json-1.3.6, open4-1.3.0, rack-1.4.1, rack-rewrite-1.2.1, rake-0.9.2.2, rubygems-bundler-0.9.0, rvm-1.11.3.3, sass-3.2.1, sass-3.2.0, therubyracer-0.10.2, thin-1.4.1, thor-0.16.0, uglifier-1.2.7, yui-compressor-0.9.6] (Gem::LoadError)
    from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems.rb:1231:in `gem'
    from /Users/gary/.rvm/gems/ruby-1.9.3-p194@ir/bin/iridium:22:in`<main>'
garymac:source gary$ iridium app test
/Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find iridium (>= 0) amongst [POpen4-0.1.4, Platform-0.4.0, activesupport-3.2.8, bundler-1.1.5, bundler-1.1.3, chunky_png-1.2.6, coffee-script-2.2.0, coffee-script-source-1.3.3, commonjs-0.2.6, compass-0.12.2, daemons-1.1.9, eventmachine-0.12.10, execjs-1.4.0, fssm-0.2.9, i18n-0.6.0, less-2.2.1, libv8-3.3.10.4-x86_64-darwin-11, multi_json-1.3.6, open4-1.3.0, rack-1.4.1, rack-rewrite-1.2.1, rake-0.9.2.2, rubygems-bundler-0.9.0, rvm-1.11.3.3, sass-3.2.1, sass-3.2.0, therubyracer-0.10.2, thin-1.4.1, thor-0.16.0, uglifier-1.2.7, yui-compressor-0.9.6] (Gem::LoadError)
    from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems.rb:1231:in `gem'
    from /Users/gary/.rvm/gems/ruby-1.9.3-p194@ir/bin/iridium:22:in`<main>'
garymac:source gary$

**Comment by ahawkins** [comment]
You have to use `bundle exec iridium`. Every crashing example you posted is without `bundle exec`.

```
garymac:source gary$ iridium app test

/Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in to_specs': Could not find iridium (>= 0) amongst [POpen4-0.1.4, Platform-0.4.0, activesupport-3.2.8, bundler-1.1.5, bundler-1.1.3, chunky_png-1.2.6, coffee-script-2.2.0, coffee-script-source-1.3.3, commonjs-0.2.6, compass-0.12.2, daemons-1.1.9, eventmachine-0.12.10, execjs-1.4.0, fssm-0.2.9, i18n-0.6.0, less-2.2.1, libv8-3.3.10.4-x86_64-darwin-11, multi_json-1.3.6, open4-1.3.0, rack-1.4.1, rack-rewrite-1.2.1, rake-0.9.2.2, rubygems-bundler-0.9.0, rvm-1.11.3.3, sass-3.2.1, sass-3.2.0, therubyracer-0.10.2, thin-1.4.1, thor-0.16.0, uglifier-1.2.7, yui-compressor-0.9.6] (Gem::LoadError)
from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:into_spec'
from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems.rb:1231:in gem'
from /Users/gary/.rvm/gems/ruby-1.9.3-p194@ir/bin/iridium:22:in'
```

This should be: `$ bundle exec iridium app FOO`

**Comment by buzzware** [comment]
On 17/08/2012, at 2:23 PM, Adam Hawkins wrote:

> You have to use bundle exec iridium. Every crashing example you posted is without bundle exec.
> 
> garymac:source gary$ iridium app test
> 
> /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in to_specs': Could not find iridium (>= 0) amongst [POpen4-0.1.4, Platform-0.4.0, activesupport-3.2.8, bundler-1.1.5, bundler-1.1.3, chunky_png-1.2.6, coffee-script-2.2.0, coffee-script-source-1.3.3, commonjs-0.2.6, compass-0.12.2, daemons-1.1.9, eventmachine-0.12.10, execjs-1.4.0, fssm-0.2.9, i18n-0.6.0, less-2.2.1, libv8-3.3.10.4-x86_64-darwin-11, multi_json-1.3.6, open4-1.3.0, rack-1.4.1, rack-rewrite-1.2.1, rake-0.9.2.2, rubygems-bundler-0.9.0, rvm-1.11.3.3, sass-3.2.1, sass-3.2.0, therubyracer-0.10.2, thin-1.4.1, thor-0.16.0, uglifier-1.2.7, yui-compressor-0.9.6](Gem::LoadError)
> from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:into_spec'
> from /Users/gary/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems.rb:1231:in gem'
> from /Users/gary/.rvm/gems/ruby-1.9.3-p194@ir/bin/iridium:22:in'
> 
> This should be: $ bundle exec iridium app FOO
> 
> Oh! I have been doing "bundle exec iridium" just like in the read me :
> $ brew install casperjs # or upgrade
> $ bundle
> $ bundle exec iridium

 but you mean "bundle exec" _in front of every iridium command_!

When the doc says "Don't forget you must use bundle exec!" it still doesn't make this clear as the doesn't follow that on the line 

$ iridium app todos

When id did "bundle exec iridium app todos" it worked.

Thanks,

Gary
